name: TEST-CICD-EC2

on:
  workflow_dispatch:
    branches: [mr9bady/test-repo]
    
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: logine to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: build docker image
        run: docker build -t test-nodjs/test-app .
      - name: push image to the docker hub
        run: |
           docker tag test-nodjs/test-app mr9bady/test-repo:latest 
           docker push mr9bady/test-repo:latest


 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATEKEY }}
      # - name: logine to docker hub
      #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: pull image from docker hub
        run: docker pull mr9bady/test-repo:latest
      - name: run docker container
        run: docker run -d -p 5000:5000 --name mr9bady mr9bady/test-repo
        
      # - name: Set Node.js 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x
      # - name: Install Dependencies
      #   run : npm install
      # - name: Test Project
      #   run: npm test
