name: TEST-CICD-EC2

on:
  workflow_dispatch:
    branches: [mr9bady/test-repo]
    
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: logine to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: build docker image
        run: docker build -t test-nodjs/test-app .
      - name: push image to the docker hub
        run: docker tag test-nodjs/test-app mr9bady/test-repo:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATEKEY }}
      - name: docker install on ec2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOSTNAME }} << 'EOF'
            sudo apt update -y
            sudo apt install docker.io -y
            sudo systemctl start docker
            sudo chmod 666 /var/run/docker.sock
            docker system prune -a --volumes -f
          EOF
      - name: pull image from docker hub
        run: sudo docker pull test-nodjs/test-app:latest
      - name: run docker container
        run: sudo docker run -d -p 5000:5000 --name mr9bady test-nodjs/test-app
        
      # - name: Set Node.js 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x
      # - name: Install Dependencies
      #   run : npm install
      # - name: Test Project
      #   run: npm test
