name: TEST-CICD-EC2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t test-nodjs/test-app .

      - name: Push Image to Docker Hub
        run: |
          docker tag test-nodjs/test-app mr9bady/test-repo:latest
          docker push mr9bady/test-repo:latest

  deploy:
    needs: build
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATEKEY }}

      - name: Deploy to Remote Server
        run: |
          echo "Pulling Docker image from Docker Hub"
          docker pull mr9bady/test-repo:latest
          
          echo "Stopping and removing existing container (if any)"
          docker stop mr9bady || true
          docker rm mr9bady || true
          
          echo "Starting new container"
          docker run -d -p 5000:5000 --name mr9bady mr9bady/test-repo:latest
          EOF
